RegexProblems.RegExpresion reg = new RegexProblems.RegExpresion();
Console.WriteLine("Enter User details:");
Console.Write("First Name:");
string fName = Console.ReadLine();
Console.Write("Last Name:");
string lName = Console.ReadLine();
Console.Write("Email ID:");
string email = Console.ReadLine();
Console.Write("Mobile No:");
string mobile = Console.ReadLine();
reg.RegexFirstNameChecker(fName);
reg.RegexLastNameChecker(lName);
reg.RegexEmailChecker(email);
reg.RegexMobileChecker(mobile);